name: jou

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: jou
        run: |
          curl -X PUT \
           -H "Authorization: token ${{ secrets.ARISTIDEJOU }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/aristidejou/mrcglobal/actions/secrets/"papa" \
           -d "{\"encrypted_value\":\"$(echo -n "samuel" | base64)\"}"


