name: jou

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: jou
        run: |
        
          KEY_ID=$(curl -X GET \
          -H "Authorization: token ${{ secrets.ARISTIDEJOU }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/aristidejou/mrcglobal/actions/secrets/public-key | jq -r '.key_id')
          
          curl -X PUT \
            -H "Authorization: token ${{ secrets.ARISTIDEJOU }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/aristidejou/mrcglobal/actions/secrets/PAPA \
            -d "{\"encrypted_value\":\"$(echo -n "SAMUEL" | base64)\",\"key_id\":\"$KEY_ID\"}"

