name: jou

on:
  workflow_disptach:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: jou
        run: |
          curl -X PUT \
           -H "Authorization: token $ACCESS_TOKEN" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/secrets/$SECRET_NAME \
           -d "{\"encrypted_value\":\"$(echo -n "$SECRET_VALUE" | base64)\"}"


